workdir: /uru/Data/old_atium/Data/Nanopore/projects/210124_mason_bisulfite # path to save the analysis outputs
codedir: /home/gmoney/T2T-Epigenetics/bisulfite/epiQC  # path to this dir
reference: /uru/Data/old_atium/Data/Nanopore/projects/210124_mason_bisulfite/reference # path to reference genome
threads: 60 # available cores
